# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41a0aaf77ea673a8ee1e8937f18de5fa4c8538fc5066eaa850470293a87fcc4c2162404a973da84d8749115a467aa524a58797649ceda77ab4f6fb1f20ccd86f

test:
  secret_key_base: 444695ff1deef0111b747ce99e53b2fc111383de293e6d86c55a2874891c385df51ddba331b10af58b173d26a54909159fd1ee5ef41100cd4a0862e9314dbf6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
